export { default as $ }                       from 'https://raw.githubusercontent.com/lilnasy/dax/7ff8476/mod.ts'
export { fs, path, colors, which }            from 'https://raw.githubusercontent.com/lilnasy/dax/7ff8476/src/deps.ts'
export { staticText, showCursor, hideCursor } from 'https://raw.githubusercontent.com/lilnasy/dax/7ff8476/src/console/utils.ts'
export { readKeypress }                       from 'https://deno.land/x/keypress@0.0.11/mod.ts'
export { partition }                          from 'https://deno.land/std@0.182.0/collections/partition.ts'
export type * as HOT                          from 'https://esm.sh/hotscript@1.0.11'
